# T5-202: Dapr Pub/Sub Component for Kafka
# Spec: US-P5-05 (Dapr Pub/Sub Integration)
# Connects Dapr to Strimzi Kafka for event streaming

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kafka-pubsub
  namespace: default
  labels:
    app.kubernetes.io/part-of: evolution-todo
    app.kubernetes.io/component: pubsub
spec:
  type: pubsub.kafka
  version: v1
  metadata:
    # Kafka broker connection (Strimzi in-cluster)
    - name: brokers
      value: "taskflow-kafka-kafka-bootstrap.kafka.svc.cluster.local:9092"

    # Consumer group for this component
    - name: consumerGroup
      value: "todo-backend-group"

    # Authentication (none for internal Strimzi)
    - name: authType
      value: "none"

    # Message configuration
    - name: maxMessageBytes
      value: "1048576"  # 1MB

    # Consumer settings
    - name: consumeRetryInterval
      value: "100ms"

    # Enable initial offset from newest
    - name: initialOffset
      value: "newest"

    # Disable TLS for internal cluster communication
    - name: disableTls
      value: "true"

---
# Subscription configuration for backend to receive events
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: task-events-subscription
  namespace: default
spec:
  topic: task-events
  routes:
    default: /api/events/task-events
  pubsubname: kafka-pubsub

---
# Subscription for reminders topic
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: reminders-subscription
  namespace: default
spec:
  topic: reminders
  routes:
    default: /api/events/reminders
  pubsubname: kafka-pubsub
