# T5-204: Dapr Secrets Component for Kubernetes
# Spec: US-P5-05 (Dapr Integration)
# Enables Dapr to read Kubernetes secrets for secure credential management

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kubernetes-secrets
  namespace: default
  labels:
    app.kubernetes.io/part-of: evolution-todo
    app.kubernetes.io/component: secretstore
spec:
  type: secretstores.kubernetes
  version: v1
  metadata: []
  # Kubernetes secrets store reads from K8s Secrets API
  # No additional configuration needed - uses service account credentials
