# T5-203: Dapr State Store Component for PostgreSQL
# Spec: US-P5-05 (Dapr Integration)
# Connects Dapr to Neon PostgreSQL for distributed state management

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: default
  labels:
    app.kubernetes.io/part-of: evolution-todo
    app.kubernetes.io/component: statestore
spec:
  type: state.postgresql
  version: v1
  metadata:
    # Connection string from Kubernetes secret
    - name: connectionString
      secretKeyRef:
        name: todo-secrets
        key: database-url

    # Table name for state storage
    - name: tableName
      value: "dapr_state"

    # Use JSON format for state values
    - name: keyPrefix
      value: "name"

    # Enable transactions
    - name: enableTransactions
      value: "true"

    # Connection pool settings
    - name: maxConns
      value: "10"

    - name: connectionMaxIdleTime
      value: "0"

---
# Actor state store (for scheduled jobs)
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: actorstore
  namespace: default
  labels:
    app.kubernetes.io/part-of: evolution-todo
    app.kubernetes.io/component: statestore
spec:
  type: state.postgresql
  version: v1
  metadata:
    - name: connectionString
      secretKeyRef:
        name: todo-secrets
        key: database-url
    - name: tableName
      value: "dapr_actors"
    - name: keyPrefix
      value: "name"
    - name: actorStateStore
      value: "true"
